apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-hello-world.fullname" . }}
  labels:
    {{- include "flask-hello-world.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "flask-hello-world.selectorLabels" . | nindent 4 }}
