FROM jenkins/inbound-agent:latest-jdk17

USER root

# Add helm repository to apt sources
RUN apt-get update && apt-get install curl gpg apt-transport-https --yes && \
    curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey \
    | gpg --dearmor \
    | tee /usr/share/keyrings/helm.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" \
    | tee /etc/apt/sources.list.d/helm-stable-debian.list 
# Install required tools
RUN apt-get update && apt-get install -y \
    make \
    helm \
    && rm -rf /var/lib/apt/lists/*

# Switch back to the jenkins user
USER jenkins