services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Web UI
      - "50000:50000" # Agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # so Jenkins can use Docker
      - ./config/:/var/jenkins_home/casc_configs/:ro
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
    group_add:
      - 1001 # Docker group ID on the host system, adjust if necessary (eg. 'getent group docker' to find out)

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  jenkins_home:
  registry_data:
