name: flask-hello-world-pr-validator

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - src/**
      - tests/**

jobs:
  ci:
    uses: ./.github/workflows/template-app-ci.yaml
    with:
      python-version: '3.11'